import "./globals.css";
import Footer from "./components/layout/Footer";
import Header from "./components/layout/Header";
import BreadCrumb from "./components/layout/BreadCrumb";
import { Poppins } from "next/font/google";

export const metadata = {
  title: "Al-Mani Health",
  description: "Generated by create next app",
};

export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export default function RootLayout({ children }) {
  return (
    <html className={`${poppins.className} antialiased`} lang="en">
      <body>
        <Header />
        <BreadCrumb/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
