import "./globals.css";
import Footer from "./components/layout/Footer";
import Header from "./components/layout/Header";
import BreadCrumb from "./components/layout/BreadCrumb";
import { Poppins } from "next/font/google";
import CookieBar from "./components/CookieBar";

import Preloader from "./components/layout/Preloader";
export const metadata = {
  title: "Al-Mani Health",
  description: "Generated by create next app",
};

export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export default function RootLayout({ children }) {
  return (
    <html
      className={`${poppins.className} antialiased overflow-x-hidden`}
      lang="en"
    >
      <head>
        <link rel="icon" href="/images/Fav-Icon.svg" />
      </head>
      <body>
        <Header />
        <BreadCrumb />
        <CookieBar />
        <Preloader />
        {children}
        <Footer />
        <div className="lines">
          <div className="content">
            <div className="line-col" />
            <div className="line-col" />
            <div className="line-col" />
            <div className="line-col" />
            <div className="line-col" />
          </div>
        </div>
      </body>
    </html>
  );
}
